/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Paulo
 */
public class Catalogo_de_Produtos extends javax.swing.JFrame {

    /** Creates new form Catalogo_de_Produtos */
    public Catalogo_de_Produtos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catálogo de Produtos");

        jPanel1.setBackground(new java.awt.Color(14, 14, 14));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 192, 20));

        jLabel13.setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Shounen");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1180, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 185, 13));

        jLabel14.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Catálogo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel15.setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Seinen");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));

        jLabel17.setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("Romance");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2220, -1, -1));

        jLabel18.setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("Heróis");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, -1, -1));

        jPanel2.setBackground(new java.awt.Color(14, 14, 14));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Batman - o Longo dia das Bruxas.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel19.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Batman -  O Longo Dia das Bruxas");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 220, 38));

        jLabel20.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Editora: Panini");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 38));

        jLabel21.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Estoque: 17");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 38));

        jLabel22.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Vol: 1");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel16.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Preço: R$144,90");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jPanel4.setBackground(new java.awt.Color(14, 14, 14));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Batman - o Longo dia das Bruxas.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel28.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 0));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Batman -  O longo dia das bruxas");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 220, 38));

        jLabel29.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Editora: Panini");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 38));

        jLabel30.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Estoque: 25");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 38));

        jLabel31.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Vol: 1");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 38));

        jLabel32.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Preço: R$39,90");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 38));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 240, 450));

        jPanel5.setBackground(new java.awt.Color(14, 14, 14));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Batman - o Longo dia das Bruxas.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel33.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Batman -  O longo dia das bruxas");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 220, 38));

        jLabel34.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Editora: Panini");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 38));

        jLabel35.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 0));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Estoque: 25");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 38));

        jLabel36.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Vol: 1");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 38));

        jLabel37.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Preço: R$39,90");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 38));

        jPanel6.setBackground(new java.awt.Color(14, 14, 14));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Batman - o Longo dia das Bruxas.png"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel38.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 0));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Batman -  O longo dia das bruxas");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 220, 38));

        jLabel39.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 0));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Editora: Panini");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 38));

        jLabel40.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 0));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Estoque: 25");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 38));

        jLabel41.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 0));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Vol: 1");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 38));

        jLabel42.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 0));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Preço: R$39,90");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 38));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 240, 450));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 240, 450));

        jLabel49.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 0));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("ID: 20 ");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton17.setBackground(new java.awt.Color(241, 236, 64));
        jButton17.setText("Comprar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 240, 490));

        jPanel3.setBackground(new java.awt.Color(14, 14, 14));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Batman - A piada Mortal.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel23.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("ID: 19 ");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jLabel24.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Editora: Panini");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 38));

        jLabel25.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Estoque: 25");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 38));

        jLabel26.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Vol: 1");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel27.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Preço: R$39,90");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jButton1.setBackground(new java.awt.Color(241, 236, 64));
        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel48.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 0));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Batman -  A Piada Mortal");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 490));

        jPanel7.setBackground(new java.awt.Color(14, 14, 14));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Tonikaku Kawaii - vol 1.png"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel43.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 0));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Tonikaku Kawaii");
        jPanel7.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 220, 38));

        jLabel44.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 0));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Editora: Shueisha");
        jPanel7.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel45.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 0));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Estoque: 15");
        jPanel7.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel46.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 0));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Vol: 1");
        jPanel7.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel47.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 0));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Preço: R$24,90");
        jPanel7.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel50.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 0));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("ID: 35");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton31.setBackground(new java.awt.Color(241, 236, 64));
        jButton31.setText("Comprar");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 2750, 240, 490));

        jPanel8.setBackground(new java.awt.Color(14, 14, 14));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Guerra Civil.png"))); // NOI18N
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel51.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 0));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Guerra Civil");
        jPanel8.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel52.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 0));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Editora: Panini");
        jPanel8.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 38));

        jLabel53.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 0));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Estoque: 23");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 38));

        jLabel54.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 0));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Vol: 1");
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel55.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 0));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Preço: R$91,91");
        jPanel8.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel56.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 0));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("ID: 21 ");
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton18.setBackground(new java.awt.Color(241, 236, 64));
        jButton18.setText("Comprar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 240, 490));

        jPanel9.setBackground(new java.awt.Color(14, 14, 14));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Beastars vol 20.png"))); // NOI18N
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel57.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 0));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Beastars");
        jPanel9.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel58.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 0));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Editora: Panini");
        jPanel9.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel59.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 0));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Estoque: 12");
        jPanel9.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel60.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 0));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Vol: 20");
        jPanel9.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel61.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 0));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Preço: R$26,90");
        jPanel9.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel62.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 0));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("ID: 23");
        jPanel9.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton19.setBackground(new java.awt.Color(241, 236, 64));
        jButton19.setText("Comprar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 240, 490));

        jPanel10.setBackground(new java.awt.Color(14, 14, 14));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Berserk - vol 12.png"))); // NOI18N
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel63.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 0));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Berserk");
        jPanel10.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel64.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 0));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Editora: Panini");
        jPanel10.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel65.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 0));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Estoque: 8");
        jPanel10.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel66.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 0));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Vol: 12");
        jPanel10.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel67.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 0));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Preço: R$24,90");
        jPanel10.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel68.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 0));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("ID: 24");
        jPanel10.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton20.setBackground(new java.awt.Color(241, 236, 64));
        jButton20.setText("Comprar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 670, 240, 490));

        jPanel11.setBackground(new java.awt.Color(14, 14, 14));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/One Punch Man vol 1.png"))); // NOI18N
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel69.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 0));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("One Punch Man");
        jPanel11.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel70.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 0));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Editora: Panini");
        jPanel11.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel71.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 0));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Estoque: 15");
        jPanel11.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel72.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 0));
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Vol: 1");
        jPanel11.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel73.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 0));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Preço: R$24,90");
        jPanel11.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel74.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 0));
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("ID: 25 ");
        jPanel11.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton21.setBackground(new java.awt.Color(241, 236, 64));
        jButton21.setText("Comprar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 240, 490));

        jPanel12.setBackground(new java.awt.Color(14, 14, 14));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Boku no Hero vol 1.png"))); // NOI18N
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel75.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 0));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("Boku no Hero");
        jPanel12.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel76.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 0));
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("Editora: JBC");
        jPanel12.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel77.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 0));
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel77.setText("Estoque: 15");
        jPanel12.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel78.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 0));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("Vol: 1");
        jPanel12.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel79.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 0));
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("Preço: R$18,90");
        jPanel12.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel80.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 0));
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel80.setText("ID: 26");
        jPanel12.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton22.setBackground(new java.awt.Color(241, 236, 64));
        jButton22.setText("Comprar");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1210, 240, 490));

        jPanel13.setBackground(new java.awt.Color(14, 14, 14));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Boku no Hero vol 24.png"))); // NOI18N
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel81.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 0));
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("Boku no Hero");
        jPanel13.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel82.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 0));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("Editora: JBC");
        jPanel13.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel83.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 0));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("Estoque: 7");
        jPanel13.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel84.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 0));
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("Vol: 24");
        jPanel13.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel85.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 0));
        jLabel85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel85.setText("Preço: R$18,90");
        jPanel13.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel86.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 0));
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("ID: 27 ");
        jPanel13.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton23.setBackground(new java.awt.Color(241, 236, 64));
        jButton23.setText("Comprar");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1210, 240, 490));

        jPanel14.setBackground(new java.awt.Color(14, 14, 14));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/sousei no onmyouji vol 20.png"))); // NOI18N
        jPanel14.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel88.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 0));
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("Sousei no Onmyouji");
        jPanel14.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel89.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(255, 255, 0));
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText("Editora: Shueisha");
        jPanel14.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel90.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(255, 255, 0));
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel90.setText("Estoque: 7");
        jPanel14.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel91.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(255, 255, 0));
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText("Vol: 24");
        jPanel14.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel92.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(255, 255, 0));
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setText("Preço: R$27,90");
        jPanel14.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel93.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(255, 255, 0));
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel93.setText("ID: 28 ");
        jPanel14.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton24.setBackground(new java.awt.Color(241, 236, 64));
        jButton24.setText("Comprar");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1210, 240, 490));

        jPanel15.setBackground(new java.awt.Color(14, 14, 14));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Kimetsu no Yaiba vol 1.png"))); // NOI18N
        jPanel15.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel95.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(255, 255, 0));
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel95.setText("Kimetsu no Yaiba");
        jPanel15.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel96.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(255, 255, 0));
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setText("Editora: Panini");
        jPanel15.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel97.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 255, 0));
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel97.setText("Estoque: 30");
        jPanel15.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel98.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 255, 0));
        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel98.setText("Vol: 1");
        jPanel15.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel99.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 255, 0));
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel99.setText("Preço: R$24,90");
        jPanel15.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel100.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(255, 255, 0));
        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel100.setText("ID: 29 ");
        jPanel15.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton25.setBackground(new java.awt.Color(241, 236, 64));
        jButton25.setText("Comprar");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1710, 240, 490));

        jPanel16.setBackground(new java.awt.Color(14, 14, 14));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Kimetsu no Yaiba vol 8.png"))); // NOI18N
        jPanel16.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel102.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 0));
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("Kimetsu no Yaiba");
        jPanel16.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel103.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 0));
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText("Editora: Panini");
        jPanel16.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel104.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 0));
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("Estoque: 9");
        jPanel16.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel105.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 0));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("Vol: 8");
        jPanel16.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel106.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 255, 0));
        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel106.setText("Preço: R$24,90");
        jPanel16.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel107.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 0));
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel107.setText("ID: 30 ");
        jPanel16.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton26.setBackground(new java.awt.Color(241, 236, 64));
        jButton26.setText("Comprar");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1710, 240, 490));

        jPanel17.setBackground(new java.awt.Color(14, 14, 14));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel108.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Akatsuki no Yona vol 26.png"))); // NOI18N
        jPanel17.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel109.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 255, 0));
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel109.setText("Akatsuki no Yona");
        jPanel17.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 38));

        jLabel110.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 255, 0));
        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel110.setText("Editora: Hakusensha");
        jPanel17.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel111.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 255, 0));
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setText("Estoque: 15");
        jPanel17.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel112.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 255, 0));
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel112.setText("Vol: 26");
        jPanel17.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel113.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(255, 255, 0));
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setText("Preço: R$24,90");
        jPanel17.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel114.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 255, 0));
        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel114.setText("ID: 33 ");
        jPanel17.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton27.setBackground(new java.awt.Color(241, 236, 64));
        jButton27.setText("Comprar");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2250, 240, 490));

        jPanel18.setBackground(new java.awt.Color(14, 14, 14));
        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel115.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Kaguya sama vol 1.png"))); // NOI18N
        jPanel18.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel116.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(255, 255, 0));
        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel116.setText("Kaguya - Sama Love is War");
        jPanel18.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 220, 38));

        jLabel117.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(255, 255, 0));
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setText("Editora: Shueisha");
        jPanel18.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel118.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(255, 255, 0));
        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel118.setText("Estoque: 24");
        jPanel18.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel119.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(255, 255, 0));
        jLabel119.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel119.setText("Vol: 1");
        jPanel18.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel120.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(255, 255, 0));
        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel120.setText("Preço: R$24,90");
        jPanel18.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel121.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(255, 255, 0));
        jLabel121.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel121.setText("ID: 32");
        jPanel18.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton28.setBackground(new java.awt.Color(241, 236, 64));
        jButton28.setText("Comprar");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 2250, 240, 490));

        jPanel19.setBackground(new java.awt.Color(14, 14, 14));
        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel122.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Komi-san vol 3.png"))); // NOI18N
        jPanel19.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel123.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel123.setForeground(new java.awt.Color(255, 255, 0));
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setText("Komi-San Wa Komyushou Desu");
        jPanel19.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 220, 38));

        jLabel124.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel124.setForeground(new java.awt.Color(255, 255, 0));
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel124.setText("Editora: Shueisha");
        jPanel19.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel125.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(255, 255, 0));
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel125.setText("Estoque: 14");
        jPanel19.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel126.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel126.setForeground(new java.awt.Color(255, 255, 0));
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setText("Vol: 3");
        jPanel19.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel127.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(255, 255, 0));
        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel127.setText("Preço: R$24,90");
        jPanel19.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel128.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(255, 255, 0));
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel128.setText("ID: 34 ");
        jPanel19.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton29.setBackground(new java.awt.Color(241, 236, 64));
        jButton29.setText("Comprar");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 2250, 240, 490));

        jPanel20.setBackground(new java.awt.Color(14, 14, 14));
        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel129.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Catálogo - capas/Komi-san vol 19.png"))); // NOI18N
        jPanel20.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 209, 313));

        jLabel130.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(255, 255, 0));
        jLabel130.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel130.setText("Komi-San Wa Komyushou Desu");
        jPanel20.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 220, 38));

        jLabel131.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(255, 255, 0));
        jLabel131.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel131.setText("Editora: Shueisha");
        jPanel20.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jLabel132.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel132.setForeground(new java.awt.Color(255, 255, 0));
        jLabel132.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel132.setText("Estoque: 26");
        jPanel20.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 20));

        jLabel133.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel133.setForeground(new java.awt.Color(255, 255, 0));
        jLabel133.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel133.setText("Vol: 19");
        jPanel20.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 38));

        jLabel134.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel134.setForeground(new java.awt.Color(255, 255, 0));
        jLabel134.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel134.setText("Preço: R$24,90");
        jPanel20.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 38));

        jLabel135.setFont(new java.awt.Font("Broadway", 0, 16)); // NOI18N
        jLabel135.setForeground(new java.awt.Color(255, 255, 0));
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setText("ID: 36 ");
        jPanel20.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 38));

        jButton30.setBackground(new java.awt.Color(241, 236, 64));
        jButton30.setText("Comprar");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2750, 240, 490));

        jButton2.setBackground(new java.awt.Color(241, 236, 64));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagem/lupa.png"))); // NOI18N
        jButton2.setText("Buscar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        jMenu2.setText("Menu");

        jMenuItem2.setText("Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Cliente");

        jMenuItem1.setText("Cadastro de Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Produto");

        jMenuItem3.setText("Cadastro de Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Venda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        menu páginaMenu = new menu();
        páginaMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroCliente páginaCadastro = new CadastroCliente();
        páginaCadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CadastroProdutos páginaProduto = new CadastroProdutos();
        páginaProduto.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        Venda páginaVenda = new Venda();
        páginaVenda.setVisible(true);
    }//GEN-LAST:event_jButton30ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo_de_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo_de_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo_de_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo_de_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo_de_Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
